version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "5555:80"
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - app-network

  node1:
    build: ./node
    ports:
      - "8080:8080"
    environment:
      - MY_NAME=node1
    depends_on:
      - redis
    networks:
      - app-network

  node2:
    build: ./node
    ports:
      - "8080:8080"
    environment:
      - MY_NAME=node2
    depends_on:
      - redis
    networks:
      - app-network

  node3:
    build: ./node
    ports:
      - "8080:8080"
    environment:
      - MY_NAME=node3
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge